<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/header.php"; ?>
<title>Bacterial Transformation</title>
        <body>
        <div id="contentWrapper">
    
        <article>
            <h1>Phonetic Alphabet</h1>
                <div class="upperCase">
                    <ul>
                        <li>
                            <strong>A</strong>lpha
                        </li>
                        <li>
                            <strong>B</strong>ravo
                        </li>
                        <li>
                            <strong>C</strong>harlie
                        <li>
                            <strong>D</strong>elta
                        </li>
                        <li>
                            <strong>E</strong>cho
                        </li>
                        <li>
                            <strong>F</strong>oxtrot
                        </li>
                        <li>
                            <strong>G</strong>olf
                        </li>
                        <li>
                            <strong>H</strong>otel
                        </li>
                        <li>
                            <strong>I</strong>ndia
                        </li>
                        <li>
                            <strong>J</strong>uliet
                        </li>
                        <li>
                            <strong>K</strong>ilo
                        </li>
                        <li>
                            <strong>L</strong>ima
                        </li>
                        <li>
                            <strong>M</strong>ike
                        </li>
                        <li>
                            <strong>N</strong>ovember
                        </li>
                        <li>
                            <strong>O</strong>scar
                        </li>
                        <li>
                            <strong>P</strong>apa
                        </li>
                        <li>
                            <strong>Q</strong>uebec
                        </li>
                        <li>
                            <strong>R</strong>omeo
                        </li>
                        <li>
                            <strong>S</strong>ierra
                        </li>
                        <li>
                            <strong>T</strong>ango
                        </li>
                        <li>
                            <strong>U</strong>niform
                        </li>
                        <li>
                            <strong>V</strong>ictor
                        </li>
                        <li>
                            <strong>W</strong>hiskey
                        </li>
                        <li>
                            <strong>X</strong>-Ray
                        </li>
                        <li>
                            <strong>Y</strong>ankee
                        </li>
                        <li>
                            <strong>Z</strong>ulu
                        </li>
                    </ul>
                </div>
        </article>
        </div>
    </body>

<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/footer.php"; ?>